### ISSUE TITLE
add guidance for swtpm or some other software-based TPM

### ISSUE THREAD

**Issue by 4nd3r** [ohthehugemanatee/win10vm#2]
to satisfy security requirements, one might also need TPM support, but not every computer have that chip.

One possible solution is swtpm: https://github.com/stefanberger/swtpm

I'll play with it a bit and report back.

**Comment by ohthehugemanatee** [comment]
My Virt-Manager has an option in the GUI to add a TPM, and it's either of type "passthrough" or "emulated". Try that, first!

**Comment by 4nd3r** [comment]
meanwhile I got TPM module for my motherboard, so this swtpm thing is not that important for me anymore :disappointed:
